name: Deploy lib to Maven Central

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Publish to Maven Central
        run: |
          ./gradlew publishAndReleaseToMavenCentral \
            -PsigningInMemoryKey=$GPG_KEY \
            -PsigningInMemoryKeyPassword=$GPG_PASSWORD \
            -PmavenCentralUsername=$MAVEN_USERNAME \
            -PmavenCentralPassword=$MAVEN_PASSWORD
        env:
          GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGNING_KEY_ID: ${{ secrets.ANDROID_SIGNING_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.ANDROID_OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ANDROID_OSSRH_PASSWORD }}

